### ISSUE TITLE
你好，想请教一下我在训练的时候loss基本都为0

### ISSUE THREAD

**Issue by xiexu666** [xiaogangLi/tensorflow-MobilenetV1-SSD#1]
数据也是按照voc 那种标注的格式，检查了几次也没发现是什么问题

**Comment by xiaogangLi** [comment]
您好，这个问题可能是因为图像没有被正确读取到内存，你需要调试确认一下。
当前默认的训练图像是jpg格式，你可以在parameters.py中修改参数“PIC_TYPE”来改变格式。

**Comment by xiexu666** [comment]
> 您好，这个问题可能是因为图像没有被正确读取到内存，你需要调试确认一下。
> 当前默认的训练图像是jpg格式，你可以在parameters.py中修改参数“PIC_TYPE”来改变格式。

我检查了一下图片都是jpg 的格式，很奇怪在训练100轮之后 loss 又从0变为一些数值开始正常下降。
